---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: miga-web
  name: 'homepage-frontend'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: homepage-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: homepage-frontend
    spec:
      containers:
        - name: container
          image: >-
            localhost:32000/miga/miga-01-homepage:v0.0.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-frontend
  namespace: miga-web
spec:
  selector:
    app: homepage-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
apiVersion: networking.k8s.io/v1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-frontend
  namespace: miga-web
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - www.makeitgreatagain.ge
    secretName: www.makeitgreatagain.ge-cert # < cert-manager will store the created certificate in this secret.
  rules:
    - host: www.makeitgreatagain.ge
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-frontend
                port:
                  number: 8080
